# Generated by Django 5.1.6 on 2025-02-26 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0005_vendorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('specifications', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_week', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to='equipment_images/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.vendorprofile')),
            ],
        ),
    ]
