# Generated by Django 5.1.6 on 2025-02-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_not_available',
            field=models.BooleanField(default=False),
        ),
    ]
