# Generated by Django 5.1.6 on 2025-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0009_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_pricing', models.JSONField()),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promotional_campaigns', models.JSONField()),
                ('email_settings', models.JSONField()),
                ('booking_rules', models.TextField()),
            ],
        ),
    ]
