# Generated by Django 5.1.6 on 2025-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0012_alter_booking_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
