# Generated by Django 5.1.6 on 2025-03-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0013_deliveryzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('reason', models.TextField()),
            ],
        ),
    ]
