# Generated by Django 5.1.6 on 2025-03-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0016_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='is_approved',
        ),
    ]
