# Generated by Django 5.1.6 on 2025-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0017_remove_equipment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
