# Generated by Django 5.1.6 on 2025-03-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0020_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Avail_Location',
        ),
    ]
