# Generated by Django 5.1.6 on 2025-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0021_rename_location_avail_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail_location',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
