# Generated by Django 5.1.6 on 2025-03-19 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0022_avail_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.booking')),
            ],
        ),
    ]
