# Generated by Django 5.1.6 on 2025-03-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0023_deliverylocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='longitude',
        ),
    ]
