# Generated by Django 5.1.6 on 2025-03-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0024_remove_deliverylocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_pricing', models.JSONField(default=dict)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('promotional_campaigns', models.JSONField(default=list)),
                ('email_settings', models.JSONField(default=dict)),
                ('booking_rules', models.TextField(default='')),
            ],
        ),
    ]
