# Generated by Django 5.1.6 on 2025-03-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0025_platform_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformSettings',
        ),
    ]
